version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "example-lambda-stack-staging"
s3_bucket = "my-bucket"
s3_prefix = "staging/lambda/deploy"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENV=\"staging\""

[staging.deploy.parameters]
stack_name = "example-lambda-stack-staging"
s3_bucket = "my-bucket"
s3_prefix = "staging/lambda/deploy"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENV=\"staging\""

[production.deploy.parameters]
stack_name = "example-lambda-stack-production"
s3_bucket = "my-bucket"
s3_prefix = "production/lambda/deploy"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENV=\"production\""
